[package]
name = "russimp-sys"
version = "1.0.2"
authors = ["Jhonny Knaak de Vargas"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/jkvargas/russimp-sys"
categories = ["rendering", "external-ffi-bindings", "game-engines", "multimedia"]
keywords = ["assimp", "3d", "blend", "3ds", "glTF"]
repository = "https://github.com/jkvargas/russimp-sys"
description = "Raw Assimp bindings for rust"
exclude = ["/assimp"]

[lib]
name = "russimp_sys"
path = "src/lib.rs"

[features]
default = []
prebuilt = ["static-link"]
static-link = []
nozlib = []
nolibcxx = []

[build-dependencies]
bindgen = "0.59"
vcpkg = "0.2.15"
ureq = "2.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tar = "0.4"
flate2 = "1.0"
num_cpus = "1.13"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "9ab3baf"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md", install = ["assimp", "zlib"] }
x86-pc-windows-msvc = { triplet = "x86-windows-static-md", install = ["assimp", "zlib"] }
