name: russimp-sys

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  lin-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install assimp
      run: sudo bash ${GITHUB_WORKSPACE}/install_assimp.bash
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --lib --verbose

  win-build:
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: install cargo-vcpkg
      run: cargo install cargo-vcpkg
    - name: vcpkg build
      run: cargo vcpkg build
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --lib --verbose

  cargo-publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ lin-build, win-build ]
    env:
      CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install assimp
      run: sudo bash ${GITHUB_WORKSPACE}/install_assimp.bash
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: cargo publish
      continue-on-error: true
      run: cargo publish --token ${CRATESIO_TOKEN}
