name: Test

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross-platform-build:
    runs-on: ${{ matrix.target.os }}
    strategy:
      matrix:
        target:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            triple: aarch-unknown-linux-gnu
          - os: macos-latest
            triple: x86_64-apple-darwin
          - os: macos-latest
            triple: aarch64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
        features: [ 'build-assimp', 'static-link' ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          depth: 1

      - name: Cache LLVM
        id: llvm-cache
        if: runner.os == 'Linux'
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.temp }}/llvm
          key: ${{ runner.os }}-llvm-14.0

      # LLVM comes preinstalled on Windows and macOS runners
      - name: Install LLVM
        if: runner.os == 'Linux' && steps.llvm-cache.outputs.cache-hit != 'true'
        uses: KyleMayes/install-llvm-action@v1
        with:
          directory: ${{ runner.temp }}/llvm
          version: '14.0'

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target.triple }}

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --features ${{ matrix.features }} --target ${{ matrix.target.triple }}

      - name: Test
        run: cargo test --features ${{ matrix.features }} --target ${{ matrix.target.triple }}
