name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross-platform-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
#      - name: Install LLVM on Windows
#        uses: KyleMayes/install-llvm-action@v1.6.1
#        with:
#          version: '14.0'
#        if: ${{ matrix.os == 'windows-latest' }}
      - name: Install LLVM on macOS
        run: brew install llvm
        if: ${{ matrix.os == 'macos-latest' }}
      - name: Install LLVM on Linux
        run: sudo update && apt install llvm-dev libclang-dev clang
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run Tests
        run: cargo test --lib --features static-link
