name: Workflow

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: macos-latest
            triple: x86_64-apple-darwin
          - os: windows-latest
            triple: x86_64-pc-windows-msvc
        features: [ 'build-assimp', 'static-link' ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          depth: 1

      # LLVM comes preinstalled on Windows and macOS runners
      - name: Install LLVM
        if: runner.os == 'Linux' && steps.llvm-cache.outputs.cache-hit != 'true'
        uses: KyleMayes/install-llvm-action@v1
        with:
          directory: ${{ runner.temp }}/llvm
          cached: true
          version: '14.0'

      - name: Install CMake
        uses: lukka/get-cmake@latest
        with:
          useLocalCache: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target.triple }}

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target.triple }} --features ${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target.triple }} --features ${{ matrix.features }}

      - name: Package Assimp
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --target ${{ matrix.target.triple }} --bin package --features ${{ matrix.features }}
        env:
          RUSSIMP_PACKAGE_DIR: ${{ runner.temp }}/russimp

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ env.RUSSIMP_PACKAGE_DIR }}/*
          artifactContentType: application/gzip
          artifactErrorsFailBuild: true
          draft: true
          token: ${{ secrets.RUSSIMP_FORK_TOKEN }}
        env:
          RUSSIMP_PACKAGE_DIR: ${{ runner.temp }}/russimp

  release:
    name: Release
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.RUSSIMP_FORK_TOKEN }}
        env:
          RUSSIMP_PACKAGE_DIR: ${{ runner.temp }}/russimp
